# Generated by Django 2.2.4 on 2019-08-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0003_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.IntegerField(editable=False),
        ),
    ]
