# Generated by Django 2.2.4 on 2019-08-17 14:01

from django.db import migrations, models
import photoalbum.models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0005_photo_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=photoalbum.models.avatars_upload_path),
        ),
    ]
